language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
  - mkdir build && cd build
  - cmake ..
  - make

branches:
  only:
    - master

notifications:
  email: false
